parameters:
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment:  deploy_az_ae_fa_formshub_dotnet_func_apps
    displayName: 'deploy formshub func apps'
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment}}
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
      demands:
        - msbuild
        - visualstudio
        - vstest
    strategy:
      runOnce:
        deploy:
          steps:
          # Debug: Print parameter values
          - script: |
              echo "Debug: Environment parameter = ${{ parameters.environment }}"
              echo "Debug: ServiceConnection parameter = ${{ parameters.serviceConnection }}"
            displayName: 'Debug - Show Parameter Values'
            
          - template: 'apps-pipeline-az-ae-fa-formshub-functionapp-${{ parameters.environment }}.yaml'          
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}